### ISSUE TITLE
Linking on Windows requires to link also ws2_32.lib and userenv.lib

### ISSUE THREAD

**Issue by JuSiZeLa** [aws/dcv-color-primitives#23]
Using dcv-color-primitives in a Windows project requires to link also ws2_32.lib and userenv.lib.
This is probably due to the Rust runtime but it should be document.

**Comment by fabiosky** [comment]
PR open:
https://github.com/aws/dcv-color-primitives/pull/36

**Comment by fabiosky** [comment]
This was merged from https://github.com/aws/dcv-color-primitives/pull/36
and fixed since https://github.com/aws/dcv-color-primitives/releases/tag/v0.1.14

Closing.
