### ISSUE TITLE
Doesn't support imagemagick-created avifs apparently

### ISSUE THREAD

**Issue by installgentoo** [aws/dcv-color-primitives#62]
Basically opening an image like https://github.com/installgentoo/assorted_curiosities/blob/master/trash/test.avif leads to error on 

```    // Cross-correlate pixel format with planes and alignment.
    // wrapping_sub is wanted. If num_planes is 0, this turns in a very big number that
    // still represents an invalid number of planes.
    let last_src_plane = src_format.num_planes.wrapping_sub(1);
    if !pixel_format::is_compatible(src_pixel_format, width, height, last_src_plane) {
        return Err(ErrorKind::InvalidValue);
    }
```
- when this check is removed everything seems to work. I'm not sure whether this is a fault of how image-rs supplies data, or of this crate, or something else, so opening a bug here as well.

See https://github.com/image-rs/image/issues/1647 for the investigation on this.

**Comment by fabiosky** [comment]
See https://github.com/image-rs/image/issues/1647 for discussion.
In summary, the caller api (image) is not respecting the current contract of the callee (dcv-color-primitives).

Proper solution is to have dcv color primitives handle color conversion removing the multiple of two restriction.
https://github.com/aws/dcv-color-primitives/issues/65

**Comment by fabiosky** [comment]
Closed in favor of https://github.com/aws/dcv-color-primitives/issues/65
