### ISSUE TITLE
Implement I420 to Bgra conversion

### ISSUE THREAD

**Issue by fabiosky** [aws/dcv-color-primitives#8]
Extend `convert_image` to support `PixelFormat::I420` to `PixelFormat::Bgra` image conversion.

This has to be done for the following input-compatible color spaces:
1. `ColorSpace::Bt601`
2. `ColorSpace::Bt709`

**Comment by Vendrik** [comment]
#5

**Comment by fabiosky** [comment]
Issue solved by https://github.com/aws/dcv-color-primitives/pull/5
